-- Advotecate Production Schema Export
-- Generated: 2025-10-04

-- Create tables
CREATE TABLE IF NOT EXISTS audit_logs (entity_type character varying(50) NOT NULL, user_id uuid, entity_id uuid, changes jsonb, action character varying(50) NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), ip_address inet, user_agent text, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS candidate_committees (cand_election_yr integer, fec_election_yr integer, updated_at timestamp with time zone DEFAULT now(), linkage_id integer, first_synced_at timestamp with time zone DEFAULT now(), is_active boolean DEFAULT true, last_synced_at timestamp with time zone DEFAULT now(), fec_cand_id character varying(9) NOT NULL, cmte_id character varying(9) NOT NULL, cmte_tp character varying(1), cmte_dsgn character varying(1), created_at timestamp with time zone DEFAULT now(), id uuid NOT NULL DEFAULT gen_random_uuid(), candidate_id uuid NOT NULL);

CREATE TABLE IF NOT EXISTS candidate_fundraisers (id uuid NOT NULL DEFAULT gen_random_uuid(), created_by uuid NOT NULL, updated_by uuid, updated_at timestamp with time zone DEFAULT now(), created_at timestamp with time zone DEFAULT now(), conversion_rate numeric(5,2), unique_visitors integer DEFAULT 0, suggested_amounts jsonb DEFAULT '[]'::jsonb, rejection_reason text, allow_custom_amounts boolean DEFAULT true, approved_at timestamp with time zone, approval_status character varying(20) DEFAULT 'pending'::character varying, custom_image_url character varying(500), custom_description text, custom_title character varying(255), fundraiser_role character varying(20), approved_by uuid, is_primary boolean DEFAULT false, organization_id uuid NOT NULL, fundraiser_id uuid NOT NULL, candidate_id uuid NOT NULL);

CREATE TABLE IF NOT EXISTS candidates (banner_image_url character varying(500), nickname character varying(100), is_active boolean DEFAULT true, verified_by uuid, verified_at timestamp with time zone, election_year integer, id uuid NOT NULL DEFAULT gen_random_uuid(), profile_image_url character varying(500), tiktok_handle character varying(100), middle_name character varying(100), last_name character varying(100) NOT NULL, first_name character varying(100), slug character varying(255) NOT NULL, display_name character varying(255) NOT NULL, fec_cand_id character varying(9), office_type character varying(20) NOT NULL, office_state character varying(2), office_district character varying(10), party_affiliation character varying(50), bio text, campaign_platform text, website_url character varying(500), twitter_handle character varying(100), facebook_url character varying(500), instagram_handle character varying(100), youtube_url character varying(500), campaign_logo_url character varying(500), verification_status character varying(20) DEFAULT 'unverified'::character varying, status character varying(20) DEFAULT 'active'::character varying, campaign_status character varying(20), updated_by uuid, created_by uuid, updated_at timestamp with time zone DEFAULT now(), created_at timestamp with time zone DEFAULT now(), custom_fields jsonb DEFAULT '{}'::jsonb, campaign_end_date date, campaign_start_date date);

CREATE TABLE IF NOT EXISTS compliance_jurisdictions (name character varying(255) NOT NULL, disclosure_rules jsonb, contribution_limits jsonb, code character varying(10) NOT NULL, jurisdiction_type character varying(50) NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, is_active boolean DEFAULT true, reporting_requirements jsonb);

CREATE TABLE IF NOT EXISTS compliance_reports (rejection_reason text, status character varying(20) DEFAULT 'draft'::character varying, filing_confirmation_number character varying(100), created_by uuid, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, filing_receipt jsonb, report_data jsonb, filed_by uuid, organization_id uuid NOT NULL, jurisdiction_id uuid, filing_period_start date NOT NULL, filing_period_end date NOT NULL, due_date date NOT NULL, report_type character varying(50) NOT NULL, filed_at timestamp with time zone, notes text, id uuid NOT NULL DEFAULT gen_random_uuid());

CREATE TABLE IF NOT EXISTS disbursements (external_transaction_id character varying(255), id uuid NOT NULL DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, amount numeric(12,2) NOT NULL, fee_amount numeric(8,2), net_amount numeric(12,2), initiated_at timestamp with time zone, completed_at timestamp with time zone, expected_arrival_date date, actual_arrival_date date, batch_id uuid, donation_ids uuid[], reporting_period_start date, reporting_period_end date, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, created_by uuid NOT NULL, approved_by uuid, approved_at timestamp with time zone, failure_reason text, internal_notes text, memo text, reference_number character varying(100), bank_name character varying(255), routing_number text, bank_account_number text, method character varying(20) NOT NULL, status character varying(20) NOT NULL DEFAULT 'pending'::character varying, currency character varying(3) DEFAULT 'USD'::character varying);

CREATE TABLE IF NOT EXISTS donations (referrer_url text, fee_amount numeric(8,2), currency character varying(3) DEFAULT 'USD'::character varying, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, processing_fee numeric(8,2), net_amount numeric(10,2), payment_processor_data jsonb, is_recurring boolean DEFAULT false, parent_donation_id uuid, guest_donor_info jsonb, failed_at timestamp with time zone, completed_at timestamp with time zone, captured_at timestamp with time zone, authorized_at timestamp with time zone, ip_address inet, compliance_flags jsonb, is_anonymous boolean DEFAULT false, user_agent text, donor_occupation character varying(255), donor_employer character varying(255), payment_method_type character varying(50), subscription_id character varying(255), recurring_frequency character varying(20), failure_code character varying(50), failure_reason text, status character varying(20) NOT NULL DEFAULT 'pending'::character varying, payment_method_brand character varying(20), payment_method_last4 character varying(4), payment_customer_id character varying(255), id uuid NOT NULL DEFAULT gen_random_uuid(), fundraiser_id uuid, user_id uuid, payment_transaction_id character varying(255), payment_processor character varying(50) DEFAULT 'fluidpay'::character varying, organization_id uuid NOT NULL, amount numeric(10,2) NOT NULL);

CREATE TABLE IF NOT EXISTS entity_tags (entity_id uuid NOT NULL, relevance_score integer NOT NULL DEFAULT 50, is_auto_tagged boolean DEFAULT false, tag_id uuid NOT NULL, entity_type character varying(50) NOT NULL, tagged_by_user_id uuid, tagged_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, id uuid NOT NULL DEFAULT gen_random_uuid());

CREATE TABLE IF NOT EXISTS event_registrations (accessibility_needs text, notes text, reminder_sent boolean DEFAULT false, checked_in boolean DEFAULT false, checked_in_at timestamp with time zone, checked_in_by uuid, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, guest_phone character varying(20), reminder_sent_at timestamp with time zone, volunteer_availability jsonb, guest_email character varying(255), number_of_guests integer DEFAULT 0, confirmation_sent_at timestamp with time zone, volunteer_role character varying(100), guest_name character varying(255), custom_fields jsonb, registration_type character varying(20) DEFAULT 'attendee'::character varying, status character varying(20) DEFAULT 'registered'::character varying, volunteer_skills jsonb, user_id uuid, event_id uuid NOT NULL, confirmation_sent boolean DEFAULT false, id uuid NOT NULL DEFAULT gen_random_uuid(), dietary_restrictions text);

CREATE TABLE IF NOT EXISTS events (title character varying(255) NOT NULL, contact_phone character varying(20), contact_email character varying(255), instructions text, updated_by uuid, created_by uuid, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, volunteer_roles jsonb, volunteer_slots_available integer, is_active boolean DEFAULT true, accessibility_info jsonb, max_guests_per_registration integer DEFAULT 1, allow_guests boolean DEFAULT true, requires_approval boolean DEFAULT false, is_public boolean DEFAULT true, current_waitlist integer DEFAULT 0, max_waitlist integer, waitlist_enabled boolean DEFAULT false, current_attendees integer DEFAULT 0, max_attendees integer, is_virtual boolean DEFAULT false, location_data jsonb, virtual_link character varying(500), time_zone character varying(50) NOT NULL, event_type character varying(50) NOT NULL, description text, slug character varying(255) NOT NULL, end_time timestamp with time zone NOT NULL, start_time timestamp with time zone NOT NULL, organization_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), image_url character varying(500), status character varying(20) DEFAULT 'draft'::character varying);

CREATE TABLE IF NOT EXISTS fec_candidates (updated_at timestamp with time zone DEFAULT now(), cand_st character varying(2), cand_election_yr integer, sync_source character varying(50) DEFAULT 'openfec_api'::character varying, is_active boolean DEFAULT true, cand_zip character varying(9), cand_city character varying(30), cand_st2 character varying(34), cand_st1 character varying(34), cand_pcc character varying(9), cand_status character varying(1), cand_ici character varying(1), cand_office_district character varying(2), fec_cand_id character varying(9) NOT NULL, cand_name character varying(200) NOT NULL, cand_pty_affiliation character varying(3), cand_office character varying(1) NOT NULL, cand_office_st character varying(2), last_synced_at timestamp with time zone DEFAULT now(), first_synced_at timestamp with time zone DEFAULT now(), created_at timestamp with time zone DEFAULT now());

CREATE TABLE IF NOT EXISTS fec_committees (cmte_st character varying(2), first_synced_at timestamp with time zone DEFAULT now(), last_synced_at timestamp with time zone DEFAULT now(), is_active boolean DEFAULT true, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), cmte_id character varying(9) NOT NULL, cmte_nm character varying(200) NOT NULL, tres_nm character varying(90), cmte_st1 character varying(34), cmte_st2 character varying(34), cmte_city character varying(30), cmte_zip character varying(9), cmte_dsgn character varying(1), cmte_tp character varying(1), cmte_pty_affiliation character varying(3), cmte_filing_freq character varying(1), org_tp character varying(1), connected_org_nm character varying(200));

CREATE TABLE IF NOT EXISTS fec_sync_log (records_created integer DEFAULT 0, records_processed integer DEFAULT 0, duration_seconds integer, completed_at timestamp with time zone, started_at timestamp with time zone NOT NULL DEFAULT now(), id uuid NOT NULL DEFAULT gen_random_uuid(), custom_metadata jsonb DEFAULT '{}'::jsonb, triggered_by_user_id uuid, api_endpoint character varying(255), triggered_by character varying(50), notes text, api_rate_limit_remaining integer, api_response_code integer, error_message text, api_parameters jsonb, failed_records jsonb, error_details jsonb, records_failed integer DEFAULT 0, status character varying(20) NOT NULL, sync_type character varying(50) NOT NULL, records_updated integer DEFAULT 0);

CREATE TABLE IF NOT EXISTS fundraisers (last_donation_at timestamp with time zone, id uuid NOT NULL DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, goal_amount numeric(12,2), current_amount numeric(12,2) DEFAULT 0, minimum_donation numeric(8,2) DEFAULT 1.00, maximum_donation numeric(8,2), suggested_amounts jsonb DEFAULT '[]'::jsonb, start_date timestamp with time zone NOT NULL, end_date timestamp with time zone, custom_fields jsonb, allow_anonymous boolean DEFAULT false, require_address boolean DEFAULT true, require_employer_info boolean DEFAULT true, allow_recurring boolean DEFAULT true, is_active boolean DEFAULT true, unique_donors_count integer DEFAULT 0, donation_count integer DEFAULT 0, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, created_by uuid, updated_by uuid, status character varying(20) DEFAULT 'draft'::character varying, meta_description text, social_image_url character varying(500), title character varying(255) NOT NULL, slug character varying(255) NOT NULL, description text, image_url character varying(500), video_url character varying(500));

CREATE TABLE IF NOT EXISTS interest_categories (updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, color_bg character varying(7) NOT NULL, color_hex character varying(7) NOT NULL, icon_name character varying(100) NOT NULL, description text NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), slug character varying(255) NOT NULL, name character varying(255) NOT NULL, sort_order integer NOT NULL DEFAULT 0, is_active boolean DEFAULT true, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS interest_tags (slug character varying(255) NOT NULL, description text NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), category_id uuid NOT NULL, sort_order integer NOT NULL DEFAULT 0, is_active boolean DEFAULT true, metadata jsonb DEFAULT '{}'::jsonb, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, name character varying(255) NOT NULL, color_override character varying(7), icon_name character varying(100));

CREATE TABLE IF NOT EXISTS organization_members (status character varying(20) DEFAULT 'active'::character varying, role character varying(20) NOT NULL, created_by uuid, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, accepted_at timestamp with time zone, invited_at timestamp with time zone, invited_by uuid, permissions jsonb, user_id uuid NOT NULL, organization_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid());

CREATE TABLE IF NOT EXISTS organization_users (invited_at timestamp with time zone, invited_by uuid, updated_at timestamp with time zone, created_at timestamp with time zone, organization_id uuid, user_id uuid, id uuid, permissions jsonb, role character varying(20), status character varying(20), accepted_at timestamp with time zone, created_by uuid);

CREATE TABLE IF NOT EXISTS organizations (verified_at timestamp with time zone, banner_image_url character varying(500), description text, status character varying(20) DEFAULT 'active'::character varying, updated_by uuid, city character varying(100) NOT NULL, created_by uuid, street_address text NOT NULL, name character varying(255) NOT NULL, ein character varying(20), slug character varying(255) NOT NULL, state_filing_id character varying(50), website character varying(500), bank_account_number text, routing_number text, bank_name character varying(255), state character varying(2) NOT NULL, postal_code character varying(10) NOT NULL, country character varying(2) DEFAULT 'US'::character varying, fec_id character varying(20), legal_name character varying(255) NOT NULL, organization_type character varying(50) NOT NULL, email character varying(255) NOT NULL, phone character varying(20), verification_status character varying(20) DEFAULT 'pending'::character varying, id uuid NOT NULL DEFAULT gen_random_uuid(), verification_documents jsonb, logo_url character varying(500), verified_by uuid, is_active boolean DEFAULT true, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS permission_audit_log (organization_id uuid, permission_name character varying(100), action character varying(50) NOT NULL, resource_type character varying(50), id uuid NOT NULL DEFAULT gen_random_uuid(), resource_id uuid, created_at timestamp with time zone DEFAULT now(), ip_address inet, metadata jsonb, was_granted boolean, user_agent text, user_id uuid NOT NULL);

CREATE TABLE IF NOT EXISTS permissions (id uuid NOT NULL DEFAULT gen_random_uuid(), resource character varying(50) NOT NULL, action character varying(50) NOT NULL, description text, name character varying(100) NOT NULL, updated_at timestamp with time zone DEFAULT now(), created_at timestamp with time zone DEFAULT now(), is_sensitive boolean DEFAULT false, category character varying(50));

CREATE TABLE IF NOT EXISTS role_permissions (granted_at timestamp with time zone DEFAULT now(), id uuid NOT NULL DEFAULT gen_random_uuid(), permission_id uuid NOT NULL, role_type character varying(20) NOT NULL, role_name character varying(50) NOT NULL, granted_by uuid);

CREATE TABLE IF NOT EXISTS system_config (description text, updated_by uuid, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, previous_value jsonb, version integer DEFAULT 1, is_encrypted boolean DEFAULT false, is_public boolean DEFAULT false, value jsonb NOT NULL, key character varying(100) NOT NULL, category character varying(50) DEFAULT 'general'::character varying);

CREATE TABLE IF NOT EXISTS user_feed_preferences (user_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), feed_algorithm character varying(20) DEFAULT 'mixed'::character varying, show_recommended_content boolean DEFAULT true, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, content_type_preferences jsonb DEFAULT '{"events": 50, "fundraisers": 50, "organizations": 50}'::jsonb, interest_weights jsonb DEFAULT '{}'::jsonb);

CREATE TABLE IF NOT EXISTS user_interests (id uuid NOT NULL DEFAULT gen_random_uuid(), selected_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, user_id uuid NOT NULL, is_active boolean DEFAULT true, tag_id uuid NOT NULL, priority integer NOT NULL DEFAULT 3);

CREATE TABLE IF NOT EXISTS user_permissions (id uuid NOT NULL DEFAULT gen_random_uuid(), revoked_by uuid, reason text, expires_at timestamp with time zone, granted_by uuid NOT NULL, granted_at timestamp with time zone DEFAULT now(), revoked_at timestamp with time zone, permission_id uuid NOT NULL, is_granted boolean NOT NULL, organization_id uuid, user_id uuid NOT NULL);

CREATE TABLE IF NOT EXISTS users (citizenship_status character varying(20), role character varying(20) DEFAULT 'user'::character varying, status character varying(20) DEFAULT 'active'::character varying, kyc_status character varying(20) DEFAULT 'pending'::character varying, mfa_backup_codes text[], updated_by uuid, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, created_by uuid, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, profile_data jsonb DEFAULT '{}'::jsonb, mfa_enabled boolean DEFAULT false, kyc_verified_at timestamp with time zone, phone_verified boolean DEFAULT false, date_of_birth date, mfa_secret text, avatar_url character varying(500), bio text, email_verified boolean DEFAULT false, id uuid NOT NULL DEFAULT gen_random_uuid(), email character varying(255) NOT NULL, password_hash character varying(255), first_name character varying(100) NOT NULL, last_name character varying(100) NOT NULL, middle_name character varying(100), phone character varying(20), street_address text, city character varying(100), state character varying(2), postal_code character varying(10), country character varying(2) DEFAULT 'US'::character varying, employer character varying(255), occupation character varying(255));

CREATE TABLE IF NOT EXISTS volunteer_hours (id uuid NOT NULL DEFAULT gen_random_uuid());

CREATE TABLE IF NOT EXISTS volunteer_profiles (id uuid NOT NULL DEFAULT gen_random_uuid());
