version: '3.8'

services:
  # API Backend Service (Node.js/Express)
  api-backend:
    build:
      context: ./api-backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=10.229.208.3
      - DB_PORT=5432
      - DB_NAME=advotecate_payments_dev
      - DB_USER=advotecate_app_dev
      - DB_PASSWORD=XPyL97uYXWuLMyaO2nu17MbLC
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Gateway Service (KrakenD)
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      api-backend:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service (React/Vite with nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://api-gateway:8080
      - REACT_APP_ENVIRONMENT=development
      - REACT_APP_FLUIDPAY_ENVIRONMENT=sandbox
      - REACT_APP_FLUIDPAY_DOMAIN=advotecate2026
    depends_on:
      api-gateway:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge