steps:
  # Install dependencies and run tests
  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['ci']
    dir: 'backend'

  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'backend'

  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['test']
    dir: 'backend'
    env:
      - 'NODE_ENV=test'

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/advotecate-backend:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/advotecate-backend:latest',
      '-f', 'backend/Dockerfile.prod',
      'backend'
    ]

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/advotecate-backend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/advotecate-backend:latest']

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=backend/gcp-deploy.yaml
    - --image=gcr.io/$PROJECT_ID/advotecate-backend:$COMMIT_SHA
    - --cluster=$_GKE_CLUSTER
    - --location=$_GKE_ZONE
    - --namespace=default

# Substitutions for environment-specific values
substitutions:
  _GKE_CLUSTER: 'prod-supabase-cluster'
  _GKE_ZONE: 'us-central1'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY

# Build timeout
timeout: '1200s'

# Trigger configuration
trigger:
  github:
    owner: 'your-github-username'
    name: 'web-app'
    push:
      branch: '^main$'
  includedFiles:
  - 'backend/**'

# IAM permissions required:
# - Cloud Build Service Account needs GKE Developer role
# - Cloud Build Service Account needs Container Registry Admin role
# - Cloud Build Service Account needs Secret Manager Secret Accessor role