apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-config
  namespace: supabase
  labels:
    app: supabase
    component: config
data:
  # PostgreSQL Configuration
  POSTGRES_HOST: "POSTGRES_PRIVATE_IP_PLACEHOLDER"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "supabase"
  POSTGRES_USER: "supabase_admin"

  # Supabase Configuration
  SITE_URL: "https://supabase.advotecate.com"
  API_EXTERNAL_URL: "https://api.advotecate.com"
  SUPABASE_PUBLIC_URL: "https://api.advotecate.com"

  # Kong API Gateway (Internal)
  KONG_HTTP_PORT: "8000"
  KONG_HTTPS_PORT: "8443"

  # GoTrue (Authentication)
  GOTRUE_SITE_URL: "https://supabase.advotecate.com"
  GOTRUE_URI_ALLOW_LIST: "*"
  GOTRUE_DISABLE_SIGNUP: "false"
  GOTRUE_JWT_ADMIN_ROLES: "service_role"
  GOTRUE_JWT_AUD: "authenticated"
  GOTRUE_JWT_DEFAULT_GROUP_NAME: "authenticated"
  GOTRUE_JWT_EXP: "3600"
  GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
  GOTRUE_MAILER_AUTOCONFIRM: "false"
  GOTRUE_SMTP_ADMIN_EMAIL: "admin@advotecate.com"
  GOTRUE_SMTP_HOST: "smtp.gmail.com"
  GOTRUE_SMTP_PORT: "587"
  GOTRUE_SMTP_SENDER_NAME: "Advotecate"

  # PostgREST
  PGRST_DB_SCHEMA: "public,storage,graphql_public"
  PGRST_DB_ANON_ROLE: "anon"
  PGRST_DB_USE_LEGACY_GUCS: "false"
  PGRST_APP_SETTINGS_JWT_SECRET: "JWT_SECRET_PLACEHOLDER"
  PGRST_APP_SETTINGS_JWT_EXP: "3600"

  # Storage
  STORAGE_BACKEND: "gcs"
  STORAGE_S3_REGION: "us-central1"
  GLOBAL_S3_BUCKET: "advotecate-supabase-storage"

  # Realtime
  REALTIME_DB_ENC_KEY: "supabaserealtime"
  REALTIME_MAX_CONNECTIONS: "100"
  REALTIME_MAX_CHANNELS_PER_CLIENT: "100"
  REALTIME_MAX_JOINS_PER_SECOND: "100"
  REALTIME_MAX_EVENTS_PER_SECOND: "100"

  # Analytics
  LOGFLARE_SOURCE_TOKEN: "LOGFLARE_TOKEN_PLACEHOLDER"
  LOGFLARE_API_KEY: "LOGFLARE_API_KEY_PLACEHOLDER"

  # Studio
  STUDIO_DEFAULT_ORGANIZATION: "Advotecate"
  STUDIO_DEFAULT_PROJECT: "Production"

  # Functions
  FUNCTIONS_VERIFY_JWT: "false"

---
apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
  namespace: supabase
  labels:
    app: supabase
    component: secrets
type: Opaque
stringData:
  # Database passwords (will be replaced by Terraform)
  POSTGRES_PASSWORD: "POSTGRES_PASSWORD_PLACEHOLDER"
  SUPABASE_AUTH_ADMIN_PASSWORD: "AUTH_ADMIN_PASSWORD_PLACEHOLDER"
  SUPABASE_STORAGE_ADMIN_PASSWORD: "STORAGE_ADMIN_PASSWORD_PLACEHOLDER"

  # JWT and API Keys
  JWT_SECRET: "JWT_SECRET_PLACEHOLDER"
  ANON_KEY: "ANON_KEY_PLACEHOLDER"
  SERVICE_ROLE_KEY: "SERVICE_ROLE_KEY_PLACEHOLDER"

  # SMTP Configuration (Optional)
  GOTRUE_SMTP_USER: ""
  GOTRUE_SMTP_PASS: ""

  # Database URLs
  DATABASE_URL: "postgresql://supabase_admin:SUPABASE_ADMIN_PASSWORD_PLACEHOLDER@POSTGRES_PRIVATE_IP_PLACEHOLDER:5432/supabase?sslmode=require"
  AUTH_DATABASE_URL: "postgresql://supabase_auth_admin:AUTH_ADMIN_PASSWORD_PLACEHOLDER@POSTGRES_PRIVATE_IP_PLACEHOLDER:5432/supabase?sslmode=require"
  STORAGE_DATABASE_URL: "postgresql://supabase_storage_admin:STORAGE_ADMIN_PASSWORD_PLACEHOLDER@POSTGRES_PRIVATE_IP_PLACEHOLDER:5432/supabase?sslmode=require"